apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  selector:
    app: cache
  ports:
  - port: 9091
    targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'       
        'consul.hashicorp.com/transparent-proxy-exclude-inbound-ports': '9092' 
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: nicholasjackson/fake-service:v0.24.2
        env: 
        - name: NAME
          value: Cache (In and Out of the Mesh)
          name: LISTEN_ADDR
          value: 0.0.0.0:9091
        ports:
        - containerPort: 9091
      serviceAccountName: cache
